### ISSUE TITLE
IndexError: list index out of range for path_raw = all_path[0]

### ISSUE THREAD

**Issue by wasimsandhu** [zamboni-lab/SLAW#17]
I'm getting what I hope is just a usage error when I try to use SLAW with some of my data. They are Thermo Q-Exactive RAW files that were converted to mzML using MSConvert. Data files are stored in **SLAW_Test\input** and parameters text file is stored in **SLAW_Test\output**.

I used the parameters.txt from the **test_files** Github directory, but when running the above line of code without a parameters file, no parameters file is generated in **SLAW_Test\output**.

Here is the line of code I'm running in Windows Powershell:
`C:\Users\eliaslab\Downloads\SLAW_Test>docker run --rm -v input:/input -v output:/output zambonilab/slaw:latest`

And here is the error I'm getting:

`Traceback (most recent call last):`
 
`File "/wrapper_docker.py", line 120, in <module>`
    `pol = exp.guess_polarity(INPUT)`
 
`File "/pylcmsprocessing/model/experiment.py", line 109, in guess_polarity`
    `path_raw = all_path[0]`

`IndexError: list index out of range`

**Comment by wasimsandhu** [comment]
Ah you're right. I assumed starting in the directory would work, I did not know I would have to specify the full path. The following worked for me:

`docker run --rm -v C:/Users/eliaslab/Downloads/SLAW_Test/input:/input -v C:/Users/eliaslab/Downloads/SLAW_Test:/output zambonilab/slaw:latest`
