### ISSUE TITLE
singularity error with slaw data

### ISSUE THREAD

**Issue by Sunshine318** [zamboni-lab/SLAW#38]
I receive this error when run on singularity with slaw test data  

Incomplete parameters detected, completing current parameters with defaults for 'output_format'
Traceback (most recent call last):
  File "/wrapper_docker.py", line 144, in <module>
    ph = pcheck.check_parameters()
  File "/pylcmsprocessing/model/helper/parameters_handler.py", line 304, in check_parameters
    cval = self.params[param]
  File "/pylcmsprocessing/model/helper/parameters_handler.py", line 127, in __getitem__
    return get_val(self.dic,item)
  File "/pylcmsprocessing/model/helper/parameters_handler.py", line 40, in get_val
    return get_val(raw[k],path[1:])
  File "/pylcmsprocessing/model/helper/parameters_handler.py", line 40, in get_val
    return get_val(raw[k],path[1:])
KeyError: 'peaktable_filter'

**Comment by htmonkey** [comment]
The error indicates that the mandatory key 'peaktable_filter' is missing in the parameters.txt file. Did you edit it, or are you using the default?

**Comment by Sunshine318** [comment]
I am using default .

**Comment by htmonkey** [comment]
I can reproduce a similar error. There is mismatch in the parameter file and the template. 
Please run zambonilab/slaw:stable instead.

**Comment by Sunshine318** [comment]
I did try it with slaw:stable but it is just halted . Its been running for few hours on singularity on cluster. That doesnt take that long on Docker on my laptop.
singularity run -C -W workspace -B test_out:/output -B mzML:/input slaw.sif
2024-08-02|11:10:57|INFO: Total memory available: 111892 and 72 cores. The workflow will use 1575 Mb by core on 71 cores.
2024-08-02|11:10:57|INFO: Guessing polarity from file:DDA2.mzML
2024-08-02|11:11:04|INFO: Polarity detected: positive
2024-08-02|11:11:06|INFO: STEP: initialisation TOTAL_TIME:8.76s LAST_STEP:8.76s
2024-08-02|11:11:08|INFO: 4 peakpicking added
2024-08-02|11:11:49|INFO: MS2 extraction finished
2024-08-02|11:11:49|INFO: Starting peaktable filtration
2024-08-02|11:11:49|INFO: Done peaktables filtration
2024-08-02|11:11:49|INFO: STEP: peakpicking TOTAL_TIME:51.95s LAST_STEP:43.19s
2024-08-02|11:11:49|INFO: Aligning
